<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_home</name>
   <tag></tag>
   <elementGuidId>5dd86422-262e-40f7-b6f8-d31c9fdc8716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7cce9b85-972d-483c-aaa6-32cbad259803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>landing1</value>
      <webElementGuid>1a9b1f10-8c69-4166-b4fb-9fa999bb01e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/landing2.f152f7ebc283e654bbf0.png</value>
      <webElementGuid>f4f5f680-e013-4532-b88c-0a85305d8acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cover mx-auto p-10 pl-5 pb-0 w-2/5</value>
      <webElementGuid>e82fb650-c253-4e4d-8e91-59de3d8402da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex flex-col md:flex-row gap-24 pl-6&quot;]/img[@class=&quot;cover mx-auto p-10 pl-5 pb-0 w-2/5&quot;]</value>
      <webElementGuid>3f199e52-cb8d-4571-9cd5-bb2c2a55fa83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/img</value>
      <webElementGuid>9b0b27db-2286-4a47-86ad-c3602a45e9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='landing1']</value>
      <webElementGuid>e85dd0b4-9bcf-4a6f-8e70-8e81ec54faf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7045c75b-f255-4fc0-8ba5-6d56ebf65a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'landing1' and @src = '/static/media/landing2.f152f7ebc283e654bbf0.png']</value>
      <webElementGuid>15fa6814-0d9c-4804-a47d-67668f61a3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
