<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>features_button</name>
   <tag></tag>
   <elementGuidId>c4ae86be-b50e-4ca0-aec5-1694c7899abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/nav/div/div/ul/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f008688-5ec2-42d9-bc49-519a62d0c0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#features</value>
      <webElementGuid>252fad7c-5f17-4c5a-94c8-bc73f77df44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block py-3 pl-3 pr-4 text-black hover:text-[#566B55] md:hover:bg-transparent md:p-0 </value>
      <webElementGuid>3b6e588d-cbc1-4cb0-98e8-13512da1a7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Features</value>
      <webElementGuid>42c43817-58f7-46c8-82ab-ebe9178f1918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/nav[@class=&quot;border-gray-200 bg-white px-2 py-2.5 dark:border-gray-700 dark:bg-gray-800 sm:px-4 top-0 bg-gradient-to-r from-[#F5F9F5] via-[#BDD6BC] to-[#6F8A6E] fixed w-full&quot;]/div[@class=&quot;mx-auto flex flex-wrap items-center justify-between&quot;]/div[@class=&quot;w-full md:block md:w-auto hidden&quot;]/ul[@class=&quot;mt-4 flex flex-col md:mt-0 md:flex-row md:space-x-8 md:text-sm md:font-medium&quot;]/ul[@class=&quot;flex flex-col p-3 md:flex-row md:space-x-14 md:mt-0 md:text-lg md:font-medium sm:gap-2 gap-0 px-28&quot;]/li[2]/a[@class=&quot;block py-3 pl-3 pr-4 text-black hover:text-[#566B55] md:hover:bg-transparent md:p-0&quot;]</value>
      <webElementGuid>46ef0745-ced9-4aa2-bc80-8635468f3cc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/nav/div/div/ul/ul/li[2]/a</value>
      <webElementGuid>20a3a84f-e173-49c5-8ed3-7039daef9e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Features')]</value>
      <webElementGuid>375f8cdf-cfff-4e40-a36a-9cbc2ea4399c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>e30d4503-97de-45a8-ae84-1b73ac007223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open main menu'])[1]/following::a[2]</value>
      <webElementGuid>b11f55ba-50bb-43a5-9721-5fac862e5a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimonial'])[1]/preceding::a[1]</value>
      <webElementGuid>1f8adbbc-24f3-416e-a75b-0ef28ec7fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[2]</value>
      <webElementGuid>454d7128-917e-4971-aadd-fc40213d0272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Features']/parent::*</value>
      <webElementGuid>4bc9e858-cbe6-48f4-a3c5-bede0612179e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#features')]</value>
      <webElementGuid>21cb408f-9a44-4603-90d9-e8e6fa15f50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>57382406-5c3c-4f90-b279-e6648305bf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#features' and (text() = 'Features' or . = 'Features')]</value>
      <webElementGuid>87a47b1e-7826-4d7a-9aca-e8b88aa1e1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
