<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_home</name>
   <tag></tag>
   <elementGuidId>ff72397c-f2fd-40e1-82dd-f53f5127c33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3553e0bf-a80a-4b11-a71d-3d5e0b802873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>landing1</value>
      <webElementGuid>a53de76d-805c-410d-b9ec-d03277a45009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/landing2.f152f7ebc283e654bbf0.png</value>
      <webElementGuid>1804ad24-41dd-40bc-9783-4ea419411c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cover mx-auto p-10 pl-5 pb-0 w-2/5</value>
      <webElementGuid>28981e73-210d-4df7-943f-e5810d45ad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex flex-col md:flex-row gap-24 pl-6&quot;]/img[@class=&quot;cover mx-auto p-10 pl-5 pb-0 w-2/5&quot;]</value>
      <webElementGuid>6ddc37d6-91d7-4835-911a-ff1eb4840205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/img</value>
      <webElementGuid>1b136f6e-a285-4e50-8a89-a9ed78bf8426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='landing1']</value>
      <webElementGuid>3b8c40f3-602e-4726-be67-97e07a798c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>abd4fbe4-8878-489b-a245-00b0dc4e4645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'landing1' and @src = '/static/media/landing2.f152f7ebc283e654bbf0.png']</value>
      <webElementGuid>35d6430f-aa87-4aa5-a02e-66204e6dbe6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
