<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo</name>
   <tag></tag>
   <elementGuidId>950ca7d7-3c94-4142-b470-2ab303477fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/nav/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e6c4b0d4-a91b-4c5d-be7a-0e42cd02943f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/NavbarLogo.0920739fa5824838a5a7ac079c7d4968.svg</value>
      <webElementGuid>13bb279f-67e4-47f0-aedb-669fb92fc1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-3 ml-14 h-6 sm:h-9 w-100% pl-5</value>
      <webElementGuid>f99d3ada-2657-46ba-a10f-66c327b9f666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JokoMart</value>
      <webElementGuid>cb39ff6e-ad6e-468e-8744-158669b55efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/nav[@class=&quot;border-gray-200 bg-white px-2 py-2.5 dark:border-gray-700 dark:bg-gray-800 sm:px-4 top-0 bg-gradient-to-r from-[#F5F9F5] via-[#BDD6BC] to-[#6F8A6E] fixed w-full&quot;]/div[@class=&quot;mx-auto flex flex-wrap items-center justify-between&quot;]/a[@class=&quot;flex items-center&quot;]/img[@class=&quot;mr-3 ml-14 h-6 sm:h-9 w-100% pl-5&quot;]</value>
      <webElementGuid>5713b3a1-2bf5-419f-88a2-d3a8e1c89c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/nav/div/a/img</value>
      <webElementGuid>9cdfb651-c986-4d7e-b6ff-b42b1a0ebffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='JokoMart']</value>
      <webElementGuid>218e4578-9651-4e5d-9e63-8377a33bff69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5173f55a-9297-43c2-988b-52aec4ea87a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/NavbarLogo.0920739fa5824838a5a7ac079c7d4968.svg' and @alt = 'JokoMart']</value>
      <webElementGuid>915a4ea8-bc6a-474b-a5ef-403f19b2f2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
