<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login.btn</name>
   <tag></tag>
   <elementGuidId>062ed6d8-389b-405d-ad67-8435dc8abe1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;input&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;input&quot;]/button</value>
      <webElementGuid>951f191a-3599-4f81-a55f-1f6f985e2428</webElementGuid>
   </webElementProperties>
</WebElementEntity>
