<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validate_login</name>
   <tag></tag>
   <elementGuidId>be61c1ec-ab46-4eac-9511-08565c422bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div[2]/div/h2
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div[2]/div/h2
</value>
      <webElementGuid>72652ef1-3788-4c37-91ee-c4ad52646006</webElementGuid>
   </webElementProperties>
</WebElementEntity>
