<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_dashboard</name>
   <tag></tag>
   <elementGuidId>6cf59fc4-0c4d-41a1-8ba9-dec12e622d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[1]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[1]/div/img</value>
      <webElementGuid>5e4261d4-a5f5-40df-9a12-0c72fda9b2fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
