<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_product</name>
   <tag></tag>
   <elementGuidId>4eb34ee5-038d-4cd8-a937-3d1cfb4b03f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-3xl.font-bold.mb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>244e9a1d-efe0-4201-b15c-cb2671b6bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl font-bold mb-5</value>
      <webElementGuid>fe4c3c5d-9732-403e-9ab1-e3c3704c2467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Stock</value>
      <webElementGuid>f411471f-d8e1-453f-af39-9f0a2d0e1b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;flex row&quot;]/div[@class=&quot;flex flex-col w-4/5&quot;]/div[@class=&quot;mx-auto pt-5 mt-3&quot;]/p[@class=&quot;text-3xl font-bold mb-5&quot;]</value>
      <webElementGuid>5cb69c0c-295f-4ce5-970d-c7b2697a985c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/p</value>
      <webElementGuid>b06b2bbd-6958-4931-831b-a3903cbb68aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open main menu'])[1]/following::p[1]</value>
      <webElementGuid>eb65d622-24e7-48ef-b480-faf31726b24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::p[2]</value>
      <webElementGuid>35d40776-ec80-41d3-bbce-abb9436daf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::p[1]</value>
      <webElementGuid>ac5b3390-42da-4968-8d72-0496859d59cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::p[1]</value>
      <webElementGuid>1f4d4dfd-7dbe-446d-b0f3-8b82ab508915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Stock']/parent::*</value>
      <webElementGuid>26dfe25f-586e-4161-bde2-1506da15b6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>85396b21-ff3e-49f4-8fe2-b6b0ca14ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Product Stock' or . = 'Product Stock')]</value>
      <webElementGuid>7a96b5b4-129c-4c55-9eac-4ade34cd4940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
