<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact_button</name>
   <tag></tag>
   <elementGuidId>50351a08-19ea-418c-8f54-65e0f6a4fba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/nav/div/div/ul/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f340c279-381c-4cf4-b159-ce5c4004fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#footer</value>
      <webElementGuid>92f555d8-556a-4d06-86ef-4400304198b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block py-3 pl-3 pr-4 text-black hover:text-[#566B55] md:bg-transparent md:p-0 </value>
      <webElementGuid>f5325461-88e0-468e-b6a5-eda4f99efa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>1fa2e9a8-1823-48ca-90c4-24a5d4122bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/nav[@class=&quot;border-gray-200 bg-white px-2 py-2.5 dark:border-gray-700 dark:bg-gray-800 sm:px-4 top-0 bg-gradient-to-r from-[#F5F9F5] via-[#BDD6BC] to-[#6F8A6E] fixed w-full&quot;]/div[@class=&quot;mx-auto flex flex-wrap items-center justify-between&quot;]/div[@class=&quot;w-full md:block md:w-auto hidden&quot;]/ul[@class=&quot;mt-4 flex flex-col md:mt-0 md:flex-row md:space-x-8 md:text-sm md:font-medium&quot;]/ul[@class=&quot;flex flex-col p-3 md:flex-row md:space-x-14 md:mt-0 md:text-lg md:font-medium sm:gap-2 gap-0 px-28&quot;]/li[4]/a[@class=&quot;block py-3 pl-3 pr-4 text-black hover:text-[#566B55] md:bg-transparent md:p-0&quot;]</value>
      <webElementGuid>32817e32-889c-4622-a6cd-16d2add1ab87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/nav/div/div/ul/ul/li[4]/a</value>
      <webElementGuid>37be71ec-fc7d-4a66-80c1-292e2a5daa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>6e04cff7-bd84-4039-8e62-a42571a60158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimonial'])[1]/following::a[1]</value>
      <webElementGuid>12f439a4-38e5-412a-8bae-c1f9b00446e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[2]</value>
      <webElementGuid>355b750c-857b-4c93-97b8-3eb41e4fbfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How it Works'])[1]/preceding::a[3]</value>
      <webElementGuid>3e2501c7-d1ce-4d4e-b259-63874b53615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact']/parent::*</value>
      <webElementGuid>376be9be-525e-4572-a42d-8303c272c5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#footer')]</value>
      <webElementGuid>1dba91c2-0339-4bfc-9841-65af20d5d62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>f91ad8bc-a0bb-4a5a-81b9-99183b27c18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#footer' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>5d2ef971-df86-40c9-9f74-e1b9a7ab32b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
