<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_home</name>
   <tag></tag>
   <elementGuidId>fcc586f8-a6e4-4956-b118-34082f59538a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2197a73c-f174-48e8-bc52-73fef4959533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>landing1</value>
      <webElementGuid>10d4b704-104f-41f4-a388-6d68c21ae1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/landing2.f152f7ebc283e654bbf0.png</value>
      <webElementGuid>74965c60-61d9-4d1a-abe6-7cda1e1f0259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cover mx-auto p-10 pl-5 pb-0 w-2/5</value>
      <webElementGuid>255ca419-4586-4c6c-96af-b086070b2884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex flex-col md:flex-row gap-24 pl-6&quot;]/img[@class=&quot;cover mx-auto p-10 pl-5 pb-0 w-2/5&quot;]</value>
      <webElementGuid>0be002f4-5605-4cfc-824a-f97ac16868e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/img</value>
      <webElementGuid>edfb3e4b-6db6-4774-adb6-658c45f3076a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='landing1']</value>
      <webElementGuid>67879dba-958e-4a39-b20d-17fe9ea2c1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>27bf72a7-8b30-4600-89b3-26f1f7b72148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'landing1' and @src = '/static/media/landing2.f152f7ebc283e654bbf0.png']</value>
      <webElementGuid>5dde1ce9-584d-4245-8b21-ba9f57f4b035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
