<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_button</name>
   <tag></tag>
   <elementGuidId>1828f0c5-9455-4d61-8d04-79ff06bf5394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/table/tbody/tr[3]/td[8]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>96b71038-68bb-4e7e-8262-92d458a98c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/Edit.cd83a8de0b536f83edb7ef81fa3d43a7.svg</value>
      <webElementGuid>9cb126a0-e28d-47b5-9f99-3bba575b41e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-6</value>
      <webElementGuid>2c91ad28-9b9d-4798-8b66-fc474c72e6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;flex row&quot;]/div[@class=&quot;flex flex-col w-4/5&quot;]/div[@class=&quot;mx-14 pt-5 mt-3&quot;]/div[@class=&quot;relative overflow-x-auto shadow-md sm:rounded-lg&quot;]/table[@class=&quot;w-full text-left text-sm text-gray-500 dark:text-gray-400&quot;]/tbody[@class=&quot;divide-y&quot;]/tr[@class=&quot;hover:bg-gray-50 dark:hover:bg-gray-600 bg-white text-gray-900 font-medium&quot;]/td[@class=&quot;px-6 py-4&quot;]/div[@class=&quot;flex gap-3&quot;]/div[1]/img[@class=&quot;w-6&quot;]</value>
      <webElementGuid>8202f003-f7a2-4d13-9072-955f7ae2a986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/table/tbody/tr[3]/td[8]/div/div/img</value>
      <webElementGuid>f400e552-e6e4-4534-88a4-6d258904662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/div/div/img</value>
      <webElementGuid>a5f0f521-44dd-44a7-9e98-863a32891b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/Edit.cd83a8de0b536f83edb7ef81fa3d43a7.svg']</value>
      <webElementGuid>41162acc-a93e-40db-b58a-99d92b7a1216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
