<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_product_name</name>
   <tag></tag>
   <elementGuidId>dfcd8f21-1cf8-4268-a91b-e842530df7f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='base-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>529e2a6d-0c62-4dd5-928b-cc9687e1a733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae445c71-106d-4285-a756-c716cf961688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-input</value>
      <webElementGuid>35d9248d-08ae-431e-9d36-89a278d4f9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>052a7251-8e7b-4bee-ae3f-e614da94af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>contoh : Pulsa 10000</value>
      <webElementGuid>ab785f8f-2351-4013-9a42-106a1258b832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#566B55] focus:border-[#6F8A6E] block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500</value>
      <webElementGuid>4ba4ee75-f2b2-4233-9049-5b134be84097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test lur 29</value>
      <webElementGuid>d614dd07-b849-4e59-9d68-9ace455d3261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editProductModal&quot;)/div[@class=&quot;relative w-full max-w-lg h-full md:h-auto rounded-lg shadow-lg&quot;]/form[@class=&quot;relative bg-white rounded-lg&quot;]/div[@class=&quot;p-6 pt-5 px-10&quot;]/div[@class=&quot;mb-4&quot;]/input[@id=&quot;base-input&quot;]</value>
      <webElementGuid>8d35a879-8be6-44dc-9d96-27d700c19779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='base-input']</value>
      <webElementGuid>75ab2be0-f61c-4668-bd6d-e106c4f25532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editProductModal']/div/form/div[2]/div[2]/input</value>
      <webElementGuid>93ee0c20-ea63-4624-ab54-3dc7e27e87c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0082238e-ea79-4f87-a3c7-9202a1852cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'base-input' and @name = 'name' and @placeholder = 'contoh : Pulsa 10000']</value>
      <webElementGuid>ffb03945-0702-4a9e-9632-c7ed52c20ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
