<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_google_play</name>
   <tag></tag>
   <elementGuidId>58b5b0e1-ee06-48cf-bcd6-3bc286ee41a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68d690c3-d6b4-4dff-a1fe-a5241dbf980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25b6cef2-c2ef-4ba4-90ac-215cc1fa85fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>google_logo Play</value>
      <webElementGuid>cd6496a4-df3d-416f-9a91-8a057c1210f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kO001e&quot;)/header[@class=&quot;S3WLMd&quot;]/nav[@class=&quot;oPjgQb&quot;]/a[@class=&quot;f0UV3d&quot;]/span[1]</value>
      <webElementGuid>00ff0a8c-7d66-4a8c-aed4-ec4689bfcde3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      <webElementGuid>32335256-dc77-4143-8ce8-b716ab763527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Games'])[1]/preceding::span[1]</value>
      <webElementGuid>9ee7b352-44f3-44c7-9780-a7311f136244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/preceding::span[6]</value>
      <webElementGuid>bacdb9d8-ba51-4639-9f9d-ede992a7254f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='google_logo Play']/parent::*</value>
      <webElementGuid>47f352c3-99d6-44f1-a5ed-b32e5e9196a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>f16be8dc-5ecf-471c-8228-0cbd9d4f8208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'google_logo Play' or . = 'google_logo Play')]</value>
      <webElementGuid>3765b931-d410-43b2-b8ff-042c4cf9f5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
