<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_home</name>
   <tag></tag>
   <elementGuidId>7bf495e2-6109-4d74-acb3-b526e1e120e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5475a2d-506b-4638-892b-17d767bf9260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>landing1</value>
      <webElementGuid>2357c9ac-c765-49dd-a1a8-f74f3e3ce7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/landing2.f152f7ebc283e654bbf0.png</value>
      <webElementGuid>8adc11a0-0c87-49c1-b9fb-c1518aabdf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cover mx-auto p-10 pl-5 pb-0 w-2/5</value>
      <webElementGuid>d35e03c4-1b61-476d-8271-3942aedde114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex flex-col md:flex-row gap-24 pl-6&quot;]/img[@class=&quot;cover mx-auto p-10 pl-5 pb-0 w-2/5&quot;]</value>
      <webElementGuid>16007d0e-aa2e-49de-bdf6-8120e9a8e758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/img</value>
      <webElementGuid>c2b6ada4-cdd1-494f-a87d-866e856de9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='landing1']</value>
      <webElementGuid>2a5cd816-1da7-4894-b4f9-d8213d61a07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>368b9aee-f335-4acc-88d0-e48c641c34ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'landing1' and @src = '/static/media/landing2.f152f7ebc283e654bbf0.png']</value>
      <webElementGuid>661bd8e0-3e7e-4e29-b600-94c020dd23d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
