<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>4743c69b-3865-4c9e-92e8-944acca50875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex.items-center.rounded-md.text-sm.px-4.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dce098a9-ab98-4154-9acf-52cddec3e2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center rounded-md text-sm px-4 py-2</value>
      <webElementGuid>9de4dd80-5275-4a50-b261-44325da87517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ae4bbf7e-c934-473f-9999-5f915e1aa0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;md:bg-cover bg-fixed&quot;]/div[@class=&quot;container font-roboto&quot;]/div[@class=&quot;container px-6 mx-auto&quot;]/div[@class=&quot;flex flex-col text-center md:text-left md:flex-row h-screen justify-evenly md:items-center&quot;]/div[@class=&quot;w-full md:w-full lg:w-6/12 mx-auto md:mx-0&quot;]/div[@class=&quot;bg-white p-8 flex flex-col drop-shadow-xl rounded-xl mx-20&quot;]/form[@class=&quot;w-full&quot;]/div[@id=&quot;input&quot;]/button[@class=&quot;text-white bg-blue-700 border border-transparent hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 disabled:hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 dark:disabled:hover:bg-blue-600 focus:!ring-2 group flex h-min items-center justify-center p-0.5 text-center font-medium focus:z-10 rounded-full mt-4 bg-[#425141] hover:bg-[#6F8A6E]&quot;]/span[@class=&quot;flex items-center rounded-md text-sm px-4 py-2&quot;]</value>
      <webElementGuid>3b554203-5600-43fe-8722-80b4a0cdbfc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input']/button/span</value>
      <webElementGuid>8e8a882f-7a38-40c5-982b-fdd6767b2758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>a002d55c-1998-49e6-ac09-3bca5e1e80b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[1]</value>
      <webElementGuid>502af1f3-3e73-4d9f-bc8f-c48a6f805f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>38dbd5db-7517-4a6f-849a-e4669aa429f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>a270100e-6eb9-4733-b810-905749006b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
