<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_admin</name>
   <tag></tag>
   <elementGuidId>cebcae57-5763-4c32-8e46-e46517a7550b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be6379ef-4c06-4108-bc77-020931265c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo.c1d8ada7955d269c6376f84adba5c8e0.svg</value>
      <webElementGuid>9012b6d6-e545-4f36-8903-0117d89770ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JokoMart</value>
      <webElementGuid>971045f8-9d6d-4ba9-8f59-a0a99809f8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer w-auto bg-[#84a282] rounded-b-[50px] pt-2 px-4 shadow-lg false</value>
      <webElementGuid>20b60276-a368-4055-af2f-9bb0848757f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;flex row&quot;]/div[@class=&quot;w-1/5 duration-200 bg-[#566B55] relative shadow-lg&quot;]/div[@class=&quot;px-3&quot;]/img[@class=&quot;cursor-pointer w-auto bg-[#84a282] rounded-b-[50px] pt-2 px-4 shadow-lg false&quot;]</value>
      <webElementGuid>7aacc830-870d-4ffe-89d5-1e94caca50d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/img</value>
      <webElementGuid>46e7914a-91e5-4216-a71c-2412a287bd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='JokoMart']</value>
      <webElementGuid>57ac54e3-6896-4220-87c8-22c7b40d627d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b4efd14a-609c-4dc0-90e8-f18247b44309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logo.c1d8ada7955d269c6376f84adba5c8e0.svg' and @alt = 'JokoMart']</value>
      <webElementGuid>c05edca5-8834-4b5b-a9be-54ba11a02ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
