<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_instagram</name>
   <tag></tag>
   <elementGuidId>7a51177e-0259-4c15-a370-1adb20e106ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_AK']/div/div/div/div/div/div/div/div/section/main/article/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>82f88858-7faf-42f7-b648-a34fa17b2d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visualcompletion</name>
      <type>Main</type>
      <value>css-img</value>
      <webElementGuid>221bc112-1875-4c91-bbc3-8296685e12ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Instagram</value>
      <webElementGuid>2a49a17e-b551-4c0e-98fb-00e29281dcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13865961-bcea-4b6f-9885-e762ef952eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_AK&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x10cihs4 x1t2pt76 x1n2onr6 x1ja2u2z&quot;]/section[@class=&quot;_a997 _a998&quot;]/main[@class=&quot;_a993 _a995&quot;]/article[@class=&quot;x1qjc9v5 x6umtig x1b1mbwd xaqea5y xav7gou x9f619 x78zum5 x1q0g3np x1iyjqo2 x2lah0s xk390pu xl56j7k xg87l8a xkrivgy xat24cr x1gryazu x1ykew4q xexx8yu x4uap5 x1gan7if xkhd6sd x11njtxf xh8yej3 x1d2lwc3&quot;]/div[@class=&quot;_ab1y&quot;]/div[@class=&quot;_ab21&quot;]/div[@class=&quot;_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abal _abc5 _abcm&quot;]/div[1]/i[1]</value>
      <webElementGuid>b97e407d-8d61-4dd7-96df-efe01bc48e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_AK']/div/div/div/div/div/div/div/div/section/main/article/div[2]/div/div/div/i</value>
      <webElementGuid>b27c2586-cada-45a6-b418-aca959ca7fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>5d66ff71-5082-4eea-9565-2660cbc89024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
