<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wa_button</name>
   <tag></tag>
   <elementGuidId>57031635-44e3-4ed5-ab03-0afa5872fb6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;footer&quot;]/div/div[1]/div[1]/div[1]/a[2]/button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;footer&quot;]/div/div[1]/div[1]/div[1]/a[2]/button</value>
      <webElementGuid>fe205778-0536-46f1-8253-41d86b244c7d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
