<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_wa</name>
   <tag></tag>
   <elementGuidId>da548ef3-0761-425e-a431-3df10ef190d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.landing-headerTitle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div[3]/div[1]/div/div[1]/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div/div[3]/div[1]/div/div[1]/div</value>
      <webElementGuid>d87c8d35-caec-4305-9c65-dbb51ac9fb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div</value>
      <webElementGuid>02af2ea3-06ef-48c3-97ed-c7c63b0d651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To use WhatsApp on your computer:'])[1]/preceding::div[1]</value>
      <webElementGuid>c57d95d9-563f-40db-8513-fe48a29533f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open WhatsApp on your phone'])[1]/preceding::div[2]</value>
      <webElementGuid>9bbfccc9-5d1b-475c-9d29-274866ac61d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WhatsApp Web']/parent::*</value>
      <webElementGuid>662a338c-4e1f-4b02-813d-21bbfbe2f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>4833627b-0bb8-4b02-88f0-a6ffedc4d26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WhatsApp Web' or . = 'WhatsApp Web')]</value>
      <webElementGuid>dcc0984f-2b11-4882-8dd3-ca52716bd36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
