<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validate_login_negative</name>
   <tag></tag>
   <elementGuidId>a20411bc-ca7e-4157-bd0a-f72bf1c1513d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div[1]/img</value>
      <webElementGuid>43d4a95d-dead-445d-9e66-684f8ae88801</webElementGuid>
   </webElementProperties>
</WebElementEntity>
