<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_home</name>
   <tag></tag>
   <elementGuidId>8e4363c3-de4a-468a-b5f7-4527447c9bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>96ee3048-df85-4e20-b0fb-56c0f8a49886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>landing1</value>
      <webElementGuid>7f069c54-1198-4f9b-849a-1ba328f0e8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/landing2.f152f7ebc283e654bbf0.png</value>
      <webElementGuid>5e606296-7b8f-4fdc-a30a-ee3e1515755e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cover mx-auto p-10 pl-5 pb-0 w-2/5</value>
      <webElementGuid>b591f88d-3ccb-4314-a7fa-71d533164643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex flex-col md:flex-row gap-24 pl-6&quot;]/img[@class=&quot;cover mx-auto p-10 pl-5 pb-0 w-2/5&quot;]</value>
      <webElementGuid>5de2d3a6-5f25-4233-adb7-b54aa3761b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/img</value>
      <webElementGuid>a0d44809-d728-401e-9938-e296000d66c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='landing1']</value>
      <webElementGuid>7bbc84f1-7358-4d14-ae0c-0721004fe29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b289ecf9-879f-4a9c-b5c5-1c3d58bc29ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'landing1' and @src = '/static/media/landing2.f152f7ebc283e654bbf0.png']</value>
      <webElementGuid>bacd503a-e368-4b54-81b4-12b8ced78123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
